### PR TITLE
Update org.lenmus.lenmus.desktop

### PR DESCRIPTION
**Pull request by trebmuh**
I believe that the English "A free program to learn music" refers to "free as a free speech", and not "free as a free beer".

### CODE REVIEW

**Comment by cecilios** [comment]
In this case it is both as this is not a commercial project.  In Spanish, I've translated it as 'gratuito', also in other latin languages such as Galician or Italian, the translators preferred  'gratuito' term. Anyway, you know better than me what term will be better understood in French speaking countries. Do you confirm this change?

**Comment by trebmuh** [comment]
In French, we usually use as follow:
1. "gratuit" when it's about a "free as a free beer" software
2. "libre" when it's about a "free as a free speech" software
Usually, 2 implies 1.

**Comment by trebmuh** [comment]
@cecilios : thanks for the merge. Can you please answer the question in my previous message?

**Comment by cecilios** [comment]
On both. No one is more important than the other one. Both are equaly important to me.

**Comment by trebmuh** [comment]
OK. Then I think that "libre" is better than "gratuit" in this case, because it makes a difference with the "proprietary freeware".
Thanks for your quick answer!

**Comment by cecilios** [comment]
Thanks, I now understand your point!

**Pull request merged**
